create table if not exists public.backtest_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null,
  window_days integer not null,
  settled_bets integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  hit_rate numeric not null default 0,
  roi numeric not null default 0,
  pnl_units numeric not null default 0,
  total_stake_units numeric not null default 0,
  avg_ev numeric not null default 0,
  max_drawdown numeric not null default 0,
  created_at timestamptz not null default now(),
  unique(snapshot_date, window_days)
);

create index if not exists backtest_snapshots_date_idx
  on public.backtest_snapshots (snapshot_date desc);
