-- Append-only jurnal pentru fiecare rulare /api/history?sync=1 (cron sau JWT).
create table if not exists public.history_sync_log (
  id bigint generated by default as identity primary key,
  ran_at timestamptz not null default now(),
  source text not null,
  method text not null,
  ok boolean not null,
  scanned integer not null default 0,
  updated integer not null default 0,
  error text
);

create index if not exists history_sync_log_ran_at_idx
  on public.history_sync_log (ran_at desc);

alter table public.history_sync_log enable row level security;

drop policy if exists "service_only_history_sync_log" on public.history_sync_log;
create policy "service_only_history_sync_log"
on public.history_sync_log
for all
using (false);

comment on table public.history_sync_log is 'Append-only sync journal for /api/history?sync=1. View in Supabase Table Editor.';
